CREATE TABLE TB_USER_ADDR(
UA_NUM INTEGER PRIMARY KEY,
UA_PRIVINCE VARCHAR2(20),
UA_CITY VARCHAR2(20),
UA_DISTRICT VARCHAR2(20),
UA_DONG VARCHAR2(20),
UA_STREET VARCHAR2(20),
UA_POSTALNUM INTEGER);

CREATE TABLE TB_DELIVERY(
D_NUM INTEGER PRIMARY KEY,
D_STATUS VARCHAR2(20),
D_COMPANY VARCHAR2(10),
D_DATE VARCHAR2(10),
D_TIME VARCHAR2(10),
D_LOCATION VARCHAR2(10),
D_ARRIVETIME VARCHAR2(20));

CREATE TABLE TB_PRODUCT_OPTION(
O_NUM INTEGER PRIMARY KEY,
O_NAME VARCHAR2(20),
O_PRICE INTEGER);

CREATE TABLE TB_PRODUCT_IMAGE(
I_NUM INTEGER PRIMARY KEY,
I_FRONT VARCHAR2(50),
I_RIGHT VARCHAR2(50),
I_LEFT VARCHAR2(50),
I_BACK VARCHAR2(50));

CREATE TABLE TB_DASHBOARD(
DB_NUM INTEGER PRIMARY KEY,
DB_CATEGORY VARCHAR2(10),
DB_PRODUCT INTEGER,
DB_SORT VARCHAR2(20));

CREATE TABLE TB_PRODUCT(
P_NUM INTEGER PRIMARY KEY,
P_NAME VARCHAR2(30),
P_PRICE INTEGER,
P_AMOUNT INTEGER,
P_OPTION INTEGER,
P_IMAGE INTEGER,
FOREIGN KEY(P_OPTION) REFERENCES TB_PRODUCT_OPTION(O_NUM),
FOREIGN KEY(P_IMAGE) REFERENCES TB_PRODUCT_IMAGE(I_NUM));

ALTER TABLE TB_DASHBOARD ADD CONSTRAINT addkey FOREIGN KEY(DB_PRODUCT) REFERENCES TB_PRODUCT(P_NUM);

CREATE TABLE TB_BASKET(
B_NUM INTEGER PRIMARY KEY,
B_PNUM INTEGER,
B_PNAME VARCHAR(30),
B_PRICE INTEGER,
B_AMOUNT INTEGER,
FOREIGN KEY (B_PNUM) REFERENCES TB_PRODUCT(P_NUM));


CREATE TABLE TB_USER(
U_ID VARCHAR2(30) PRIMARY KEY,
U_PASSWORD VARCHAR2(40),
U_NAME VARCHAR2(10),
U_PNUM VARCHAR2(20),
U_EMAIL VARCHAR2(40),
U_ADDR INTEGER,
U_BASKET INTEGER,
U_DELIVERY INTEGER,
FOREIGN KEY(U_ADDR) REFERENCES TB_USER_ADDR(UA_NUM),
FOREIGN KEY(U_BASKET) REFERENCES TB_BASKET(B_NUM),
FOREIGN KEY(U_DELIVERY) REFERENCES TB_DELIVERY(D_NUM)
);

CREATE TABLE TB_RECENTLY(
R_NUM INTEGER PRIMARY KEY,
R_PRODUCT INTEGER,
R_USERINFO VARCHAR(30),
FOREIGN KEY(R_PRODUCT) REFERENCES TB_PRODUCT(P_NUM),
FOREIGN KEY(R_USERINFO) REFERENCES TB_USER(U_ID));

CREATE TABLE TB_PAYMENT(
PM_NUM INTEGER PRIMARY KEY,
PM_PRICE INTEGER,
PM_METHOD VARCHAR2(20),
PM_DISCOUNT VARCHAR2(20),
PM_USERINFO VARCHAR2(30),
FOREIGN KEY (PM_PRICE) REFERENCES TB_BASKET(B_NUM),
FOREIGN KEY (PM_USERINFO) REFERENCES TB_USER(U_ID));